### ISSUE TITLE
Bug from state saving deliberation data

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#1167]
`/home/jpschewe/fll1/current/web/WEB-INF/bug_2024-02-19_13-108691676869785997174.zip`

**Comment by jpschewe** [comment]
I think this is resolved, however it would be good to not have "null" in the server winners, perhaps?

```
2024-02-18 17:48:36,156 [http-nio-30001-exec-3] INFO fll.tomcat.Log4jAccessLog [] {}- 192.168.47.10 127.0.0.1 "DELETE /api/AwardsScript/NonNumericOverallAwardWinners/Motivate/null HTTP/1.1" 400 C55EA9346974257BF98E6B342ABFE351
2024-02-18 17:48:36,155 [http-nio-30001-exec-4] INFO fll.tomcat.Log4jAccessLog [] {}- 192.168.47.10 127.0.0.1 "PUT /api/AwardsScript/NonNumericOverallAwardWinners/Motivate/54961 HTTP/1.1" 200 C55EA9346974257BF98E6B342ABFE351
2024-02-18 17:48:36,156 [http-nio-30001-exec-10] INFO fll.tomcat.Log4jAccessLog [] {}- 192.168.47.10 127.0.0.1 "PUT /api/AwardsScript/NonNumericOverallAwardWinners/Rising%20All-Star/3927 HTTP/1.1" 200 C55EA9346974257BF98E6B342ABFE351
2024-02-18 17:48:36,158 [http-nio-30001-exec-7] ERROR fll.web.api.awardsScript.NonNumericOverallAwardWinners [] {}- doPut: team number is not parsable: 'null'
java.lang.NumberFormatException: For input string: "null"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at fll.web.api.awardsScript.AwardWinnerApiUtils.parsePutPathInfo(AwardWinnerApiUtils.java:61) [classes/:?]
        at fll.web.api.awardsScript.NonNumericOverallAwardWinners.doDelete(NonNumericOverallAwardWinners.java:158) [classes/:?]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:553) [jakarta.servlet-api-6.0.0.jar:6.0.0]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) [jakarta.servlet-api-6.0.0.jar:6.0.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) [tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.7.jar:10.1.7]
```

**Comment by jpschewe** [comment]
This has been fixed in the final deliberation implementation.
