### ISSUE TITLE
Look into embedded Tomcat

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#713]
An alternative to #296 is to use embedded Tomcat.

The end goal is to get rid of the system exec calls to start the webserver and stop the dos window from coming up on Windows. Trying tomcat-embed first as that may have fewer issues with the transition. I found a guide at https://devcenter.heroku.com/articles/create-a-java-web-application-using-embedded-tomcat. I've manually downloaded all of the dependencies (until issue #696 is done). I've added the libraries to the build and removed the external tomcat libraries from the build. That all builds. Now I need to try the launcher.

Tasks:
  - [x] make sure no missing jars are in the classpath (currently have issue with findbugs and tomcat embed)
  - [x] get logging going to log4j
  - [x] check logs for errors from tomcat as part of the build
  - [x] get running from main launcher
  - [x] how to run tests?
    - currently using a separate web app name
    - [x] see if we can create a parallel classes directory only and use that
      - use `addPreResources` to set the appropriate classes directory based on `inside.test`
  - [x] root web application at /
    - since the class files are switched out based on a property, we can make this work
    - [x] modify documentation to remove "fll-sw" from the path
      - no need to edit `gh-pages` since those URLs aren't on the main page
  - [x] how to launch for tests?
  - [x] how to handle cobertura test coverage
  - [x] Move webapps to top of build directory
    - currently in a directory expected for expanded tomcat
  - [x] how to do jsp compilation to catch compilation errors
  - [x] remove full tomcat distribution
  - [x] clean up build.xml for removed full tomcat
  - [x] xml-apis warning (see comments)
  - [x] JDBC shutdown warnings (see comments)
    - ignoring this, it's only happening when everything shuts down and then Tomcat is doing the right thing anyway.
  - [x] warning about fork join worker not shutdown
    - ignore this, we use a thread pool to check for hostnames in the background. And it appears the memory leak is fixed with Java 9.

**Comment by jpschewe** [comment]
Needed to add a call to `tomcat.getConnector()` to add the default connector for newer versions of tomcat.

**Comment by jpschewe** [comment]
Some warnings on shutdown that need to be resolved.
```
WARNING: The web application [fll-sw] registered the JDBC driver [org.hsqldb.jdbc.JDBCDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Feb 05, 2019 6:55:19 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [fll-sw] appears to have started a thread named [ForkJoinPool.commonPool-worker-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
```

It's also the case that the webserver doesn't completely shutdown on stop.

**Comment by jpschewe** [comment]
Warning to try and remove. Not sure how `xml-apis.jar` is getting into the classpath without a version number.
```
WARNING: Failed to scan [file:/C:/Users/fll/jenkins/workspace/FLL-SW_issue_713_embed-tomcat/lib/test/htmlunit/xml-apis.jar] from classloader hierarchy
java.io.FileNotFoundException: C:\Users\fll\jenkins\workspace\FLL-SW_issue_713_embed-tomcat\lib\test\htmlunit\xml-apis.jar (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
```

**Comment by jpschewe** [comment]
I'm not seeing the warning about xlml-apis.jar now. I think that this got solved with the recent fixes to the classpath.
