### ISSUE TITLE
Error message for duplicate performance score

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#973]
This error should have a more friendly error message. When a duplicate performance score is being entered it would be nice if the user got a friendly error message rather than a bug report message.

```
2021-11-01 19:22:03,972 [http-nio-19080-exec-1] ERROR fll.web.scoreEntry.SubmitScoreEntry [] {}- java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; PERFORMANCE_PK table: PERFORMANCE
java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; PERFORMANCE_PK table: PERFORMANCE
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.jdbc.JDBCStatement.executeUpdate(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at fll.db.Queries.insertPerformanceScore(Queries.java:436) ~[classes/:?]
	at fll.db.Queries.insertPerformanceScore(Queries.java:352) ~[classes/:?]
	at fll.web.scoreEntry.SubmitScoreEntry.processRequest(SubmitScoreEntry.java:81) [classes/:?]
	at fll.web.BaseFLLServlet.doGet(BaseFLLServlet.java:37) [classes/:?]
	at fll.web.BaseFLLServlet.doPost(BaseFLLServlet.java:27) [classes/:?]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:520) [jakarta.servlet-api-5.0.0.jar:5.0.0]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) [jakarta.servlet-api-5.0.0.jar:5.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-10.0.12.jar:10.0.12]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at fll.web.FooterFilter.doFilter(FooterFilter.java:51) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at fll.web.InitFilter.doFilter(InitFilter.java:110) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:872) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1695) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-10.0.12.jar:10.0.12]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; PERFORMANCE_PK table: PERFORMANCE
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.Constraint.getException(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.index.IndexAVL.insert(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.TransactionManagerMVCC.addInsertAction(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.Session.addInsertAction(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.Session.executeDirectStatement(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.6.0.jar:2.6.0]
	... 37 more
```

**Comment by bruceHighTechKids** [comment]
It would be nice to be able to get back to the scoring values too.

**Comment by jpschewe** [comment]
Can you explain more here? What do you mean by "the scoring values"?

**Comment by bruceHighTechKids** [comment]
To get this error, the user (Referee) has entered a team's score on the tablet, then hit submit.  After this error occurs, the typical reaction is to hit the browser's back button to see what information was attempted to be submitted.

However, this action does not recover the submitted information in its current form.

If the fix does not move to another screen, no action is needed.  However, if the user is taken to a new screen, the scoring run's values are lost.

**Comment by jpschewe** [comment]
Getting back to the previous screen with the scores won't help. If 2 refs pick the same team at the same time, the first one can commit, the second one needs to start over and select the correct team and score them.

**Comment by jpschewe** [comment]
I've made changes that will report an error message to the user on a duplicate performance score. When a performance score is successfully entered a success message is displayed as well. Hopefully between the two messages the refs will see the messages.
